# Feel free to disable non-critical HA parts during devel by commenting out
# Generated in hadk by executing: cd $ANDROID_ROOT; rpm/helpers/add_new_device.sh

Description: Pattern with packages for n7100 configurations
Name: jolla-configuration-n7100
Requires:
- pattern:jolla-hw-adaptation-n7100
- pattern:jolla-configuration-sfe

Summary: Jolla Configuration n7100

